@echo off

@REM Set system & User Environment variables & ADD to PATH @ Windows OS Machine cmdlet (.bat).

@REM User
setx Path "%Path%;%ProgramFiles(x86)%\NVIDIA Corporation\PhysX\Common\"
setx Path "%Path%;%ProgramFiles(x86)%\NVIDIA Corporation\NVIDIA NvDLISR\"
setx Path "%Path%;%SystemRoot%\system32\"
setx Path "%Path%;%ProgramFiles%\MATLAB\R2021a\bin\"
setx Path "%Path%;%ProgramFiles%\dotnet\"
setx Path "%Path%;%ProgramFiles%\nodejs\"
setx Path "%Path%;%SystemDrive%\php-8.2.9\"
setx Path "%Path%;%ProgramData%\ComposerSetup\bin\"
setx Path "%Path%;%ProgramFiles%\Git\cmd\"
setx Path "%Path%;%ProgramData%\Anaconda3\Scripts\anaconda-navigator.exe\"
setx Path "%Path%;%LocalAppData%\Programs\Python\Python311\Scripts\"
setx Path "%Path%;%LocalAppData%\Programs\Microsoft VS Code\bin\"
setx Path "%Path%;%SystemRoot%\WindowsPowerShell\v1.0\"
setx Path "%Path%;%SystemRoot%\Wbem\"
setx Path "%Path%;%SystemRoot%\OpenSSH\"
rem Set system environment variables & add them to Path.

@REM System
setx /M Path "%Path%;%ProgramFiles(x86)%\NVIDIA Corporation\PhysX\Common\"
setx /M Path "%Path%;%ProgramFiles%\NVIDIA Corporation\NVIDIA NvDLISR\"
setx /M Path "%Path%;%SystemRoot%\system32\"
setx /M Path "%Path%;%ProgramFiles%\MATLAB\R2021a\bin\"
setx /M Path "%Path%;%ProgramFiles%\dotnet\"
setx /M Path "%Path%;%ProgramFiles%\nodejs\"
setx /M Path "%Path%;%SystemDrive%\php-8.2.9\"
setx /M Path "%Path%;%ProgramData%\ComposerSetup\bin\"
setx /M Path "%Path%;%ProgramFiles%\Git\cmd\"
setx /M Path "%Path%;%ProgramData%\Anaconda3\Scripts\anaconda-navigator.exe\"
setx /M Path "%Path%;%LocalAppData%\Programs\Python\Python311\Scripts\"
setx /M Path "%Path%;%LocalAppData%\Programs\Microsoft VS Code\bin\"
setx /M Path "%Path%;%SystemRoot%\WindowsPowerShell\v1.0\"
setx /M Path "%Path%;%SystemRoot%\Wbem\"
setx /M Path "%Path%;%SystemRoot%\OpenSSH\"
setx /M Path "%Path%;%LocalAppData%\Programs\Python\Python311\Scripts\"

@REM setx PhysX "%ProgramFiles(x86)%\NVIDIA Corporation\PhysX\Common\" && setx Path "%Path%;%ProgramFiles(x86)%\NVIDIA Corporation\PhysX\Common\"
@REM setx NvDLISR "%ProgramFiles(x86)%\NVIDIA Corporation\NVIDIA NvDLISR\" && setx Path "%Path%;%ProgramFiles(x86)%\NVIDIA Corporation\NVIDIA NvDLISR\"
@REM setx system32 "%SystemRoot%\system32\" && setx Path "%Path%;%SystemRoot%\system32\"
@REM setx MATLAB "%ProgramFiles%\MATLAB\R2021a\bin\" && setx Path "%Path%;%ProgramFiles%\MATLAB\R2021a\bin\"
@REM setx dotnet "%ProgramFiles%\dotnet\" && setx Path "%Path%;%ProgramFiles%\dotnet\"
@REM setx nodejs "%ProgramFiles%\nodejs\" && setx Path "%Path%;%ProgramFiles%\nodejs\"
@REM setx php-8.2.9 "%SystemDrive%\php-8.2.9\" && setx Path "%Path%;%SystemDrive%\php-8.2.9\"
@REM setx ComposerSetup "%ProgramData%\ComposerSetup\bin\" && setx Path "%Path%;%ProgramData%\ComposerSetup\bin\"
@REM setx Git "%ProgramFiles%\Git\cmd\" && setx Path "%Path%;%ProgramFiles%\Git\cmd\"
@REM setx anaconda-navigator "%ProgramData%\Anaconda3\Scripts\anaconda-navigator.exe\" && setx Path "%Path%;%ProgramData%\Anaconda3\Scripts\anaconda-navigator.exe\"
@REM setx Python311 "%LocalAppData%\Programs\Python\Python311\Scripts\" && setx Path "%Path%;%LocalAppData%\Programs\Python\Python311\Scripts\"
@REM setx VS "%LocalAppData%\Programs\Microsoft VS Code\bin\" && setx Path "%Path%;%LocalAppData%\Programs\Microsoft VS Code\bin\"
@REM setx WindowsPowerShell "%SystemRoot%\system32\WindowsPowerShell\v1.0\" && setx Path "%Path%;%SystemRoot%\WindowsPowerShell\v1.0\"
@REM setx Wbem "%SystemRoot%\system32\Wbem\" && setx Path "%Path%;%SystemRoot%\Wbem\"
@REM setx system32 "%SystemRoot%\system32\OpenSSH\" && setx Path "%Path%;%SystemRoot%\OpenSSH\"
@REM setx Scripts "%LocalAppData%\Programs\Python\Python311\Scripts\" && setx PATH "%PATH%;%LocalAppData%\Programs\Python\Python311\Scripts\"

@REM setx /M PhysX "%ProgramFiles(x86)%\NVIDIA Corporation\PhysX\Common\" && setx /M Path "%Path%;%ProgramFiles(x86)%\NVIDIA Corporation\PhysX\Common\"
@REM setx /M NvDLISR "%ProgramFiles%\NVIDIA Corporation\NVIDIA NvDLISR\" && setx /M Path "%Path%;%ProgramFiles%\NVIDIA Corporation\NVIDIA NvDLISR\"
@REM setx /M system32 "%SystemRoot%\system32\" && setx /M Path "%Path%;%SystemRoot%\system32\"
@REM setx /M MATLAB "%ProgramFiles%\MATLAB\R2021a\bin\" && setx /M Path "%Path%;%ProgramFiles%\MATLAB\R2021a\bin\"
@REM setx /M dotnet "%ProgramFiles%\dotnet\" && setx /M Path "%Path%;%ProgramFiles%\dotnet\"
@REM setx /M nodejs "%ProgramFiles%\nodejs\" && setx /M Path "%Path%;%ProgramFiles%\nodejs\"
@REM setx /M php-8.2.9 "%SystemDrive%\php-8.2.9\" && setx /M Path "%Path%;%SystemDrive%\php-8.2.9\"
@REM setx /M ComposerSetup "%ProgramData%\ComposerSetup\bin\" && setx /M Path "%Path%;%ProgramData%\ComposerSetup\bin\"
@REM setx /M Git "%ProgramFiles%\Git\cmd\" && setx /M Path "%Path%;%ProgramFiles%\Git\cmd\"
@REM setx /M anaconda-navigator "%ProgramData%\Anaconda3\Scripts\anaconda-navigator.exe\" && setx /M Path "%Path%;%ProgramData%\Anaconda3\Scripts\anaconda-navigator.exe\"
@REM setx /M Python311 "%LocalAppData%\Programs\Python\Python311\Scripts\" && setx /M Path "%Path%;%LocalAppData%\Programs\Python\Python311\Scripts\"
@REM setx /M VS "%LocalAppData%\Programs\Microsoft VS Code\bin\" && setx /M Path "%Path%;%LocalAppData%\Programs\Microsoft VS Code\bin\"
@REM setx /M WindowsPowerShell "%SystemRoot%\system32\WindowsPowerShell\v1.0\" && setx Path "%Path%;%SystemRoot%\WindowsPowerShell\v1.0\"
@REM setx /M Wbem "%SystemRoot%\system32\Wbem\" && setx Path "%Path%;%SystemRoot%\Wbem\"
@REM setx /M System32 "%SystemRoot%\system32\OpenSSH\" && setx Path "%Path%;%SystemRoot%\OpenSSH\"
@REM setx /M Scripts "%LocalAppData%\Programs\Python\Python311\Scripts\" && setx PATH "%PATH%;%LocalAppData%\Programs\Python\Python311\Scripts\"

@REM docs: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setx


